trigger: none

jobs:
  - template: CI/job-doxygen.yml
 
  - job: MacOS
    strategy:
      matrix:
        mojave-std:
          image: macOS-10.14
          name: mojave
          version: 10.12
          buildType: "standard"
          prefix: "synergy"
        mojave-ent:
          image: macOS-10.14
          name: mojave
          version: 10.12
          buildType: "enterprise"
          prefix: "synergy-enterprise"
        catalina-std:
          image: macOS-10.15
          name: catalina
          version: 10.14
          buildType: "standard"
          prefix: "synergy"
        catalina-ent:
          image: macOS-10.15
          name: catalina
          version: 10.14
          buildType: "enterprise"
          prefix: "synergy-enterprise"
    pool:
      vmImage: $[ variables['image'] ]

    #As apparently the trigger set to none doesn't work
    condition: eq(variables['Build.Reason'], 'Manual')

    variables:
      QT_PATH: '/usr/local/opt/qt/bin'

    steps:
      - template: CI/checkout.yml
      - template: CI/MacOS/mac-build.yml

  - job: Windows
    strategy:
      matrix:
        vs2019:
          image: windows-2019
          buildType: "standard"
          prefix: "synergy"
        vs2019ent:
          image: windows-2019
          buildType: "enterprise"
          prefix: "synergy_enterprise"

    pool:
      vmImage: $[ variables['image'] ]

    #As apparently the trigger set to none doesn't work
    condition: eq(variables['Build.Reason'], 'Manual')

    variables:
      QT_VERSION: '5.12.6'
      QLI_OUT_DIR: '.\deps\Qt'
      QLI_BASE_URL: 'http://qt.mirror.constant.com/'
      QT_BIN_PATH: '$(Build.Repository.LocalPath)\$(QLI_OUT_DIR)\$(QT_VERSION)\msvc2017_64'
      QT_BIN_PATH_32: '$(Build.Repository.LocalPath)\$(QLI_OUT_DIR)\$(QT_VERSION)\msvc2017'
      BONJOUR_SDK_DIR: 'deps\BonjourSDK'
      ENV_BAT: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\vsdevcmd'

    steps:
      - template: CI/checkout.yml
      - template: CI/Windows/windows-build.yml
